version: '3'

services:
  search:
    build:
      context: ./src/search
      dockerfile: Dockerfile
    ports:
      - ${SEARCH_API_PORT}:2222
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_ADDRESS: ${MONGO_ADDRESS}
    networks:
      - docker_net

  nginx_server:
    build:
      context: ./src/nginx
      dockerfile: Dockerfile
    ports:
      - ${FRONT_PORT}:80
    networks:
      - docker_net
    depends_on:
      - search

networks:
  docker_net:
    external: false
